(function(){'use strict';
const $=id=>document.getElementById(id), HOST_ID='host'; let isHost=false,myId=null,myName='',net=null,conn=null,roster=[],roundRoster=[],wordMap=null,targetOf=null,currentRoundId=0,roundActive=false,roundEnded=false,pendingOrder=new Map(),pendingPrivate=new Map();
const setup=$('setup'),lobby=$('lobby'),game=$('game'),result=$('result'),error=$('error'),status=$('status'),start=$('start'),guessBtn=$('guess-btn');
function cleanName(v){return String(v||'').trim().slice(0,10)} function nameFor(id,list=roster){const p=list.find(x=>x.id===id);return p?p.name:id}
function renderRoster(){ $('roster').textContent=''; roster.forEach(p=>{const li=document.createElement('li');li.textContent=p.name+(p.id===myId?'（あなた）':'');$('roster').appendChild(li)}); if(isHost)start.disabled=!WordDetectiveLogic.hasMinPlayers(roster)||roster.length>WordDetectiveLogic.WORD_BANK.length; }
function broadcastRoster(){net.broadcast({type:'roster',players:roster})} function fail(m){error.textContent=m;$('host').disabled=$('join').disabled=false}
$('host').onclick=()=>{myName=cleanName($('name').value);if(!myName)return fail('ニックネームを入力してください。');isHost=true;myId=HOST_ID;$('host').disabled=$('join').disabled=true;net=WordDetectiveNet.hostRoom({onCode(c){$('room-code').textContent=c;$('host-wait').classList.remove('hidden');lobby.classList.remove('hidden');roster=WordDetectiveLogic.addPlayer(roster,{id:myId,name:myName});renderRoster()},onPeerConnected(){},onPeerMessage(id,d){if(!d||typeof d!=='object')return;if(d.type==='join'){const n=cleanName(d.name);if(!n)return;roster=WordDetectiveLogic.addPlayer(roster,{id,name:n});renderRoster();broadcastRoster()}else if(d.type==='guess')handleGuess(id,d.roundId,d.text)},onPeerDisconnected(id){roster=WordDetectiveLogic.removePlayer(roster,id);if(roundActive)abortRound();else{renderRoster();broadcastRoster()}},onError(){fail('接続中にエラーが発生しました。')}})};
$('join').onclick=()=>{myName=cleanName($('name').value);const code=$('code').value.trim();if(!myName)return fail('ニックネームを入力してください。');if(code.length!==6)return fail('6桁のコードを入力してください。');$('host').disabled=$('join').disabled=true;net=WordDetectiveNet.joinRoom(code,{onOwnId(id){myId=id},onConnected(c){conn=c;c.send({type:'join',name:myName});lobby.classList.remove('hidden');status.textContent='ホストの開始を待っています…'},onMessage:clientMessage,onDisconnected(){disconnect('ホストとの接続が切れました。')},onError(){fail('接続中にエラーが発生しました。')}})};
function clientMessage(d){if(!d||typeof d!=='object')return;const rid=Number(d.roundId);if(d.type==='roster'){roster=d.players;renderRoster()}else if(d.type==='order'&&Number.isInteger(rid)){d.roundId=rid;pendingOrder.set(rid,d);tryEnter(rid)}else if(d.type==='round-start'&&Number.isInteger(rid)){d.roundId=rid;pendingPrivate.set(rid,d);tryEnter(rid)}else if(d.type==='wrong-guess'&&rid===currentRoundId){$('guess-status').textContent='残念、違います。';guessBtn.disabled=false;$('guess-input').focus()}else if(d.type==='game-over'&&rid===currentRoundId)showResult(d);else if(d.type==='round-aborted'&&rid===currentRoundId)disconnect(d.reason)}
function tryEnter(id){const o=pendingOrder.get(id),p=pendingPrivate.get(id);if(!o||!p||id<currentRoundId)return;pendingOrder.clear();pendingPrivate.clear();currentRoundId=id;roundRoster=o.roster;enterGame(o.order,p)}
function hostStart(){if(!isHost||roundActive||!WordDetectiveLogic.hasMinPlayers(roster)||roster.length>WordDetectiveLogic.WORD_BANK.length)return;start.disabled=true;$('again').disabled=true;currentRoundId++;roundRoster=roster.map(p=>({id:p.id,name:p.name}));wordMap=WordDetectiveLogic.assignWords(roundRoster.map(p=>p.id));const chain=WordDetectiveLogic.buildTargetChain(roundRoster.map(p=>p.id));targetOf=chain.targetOf;net.broadcast({type:'order',roundId:currentRoundId,order:chain.order,roster:roundRoster});roundRoster.forEach(p=>{const payload={type:'round-start',roundId:currentRoundId,myWord:wordMap[p.id],targetId:targetOf[p.id],targetName:nameFor(targetOf[p.id],roundRoster)};if(p.id===HOST_ID)enterGame(chain.order,payload);else net.sendTo(p.id,payload)})}
start.onclick=()=>{if(!start.disabled)hostStart()};$('again').onclick=hostStart;
function enterGame(order,p){roundActive=true;roundEnded=false;setup.classList.add('hidden');lobby.classList.add('hidden');result.classList.add('hidden');game.classList.remove('hidden');$('guess-input').value='';$('word').textContent=p.myWord;$('target').textContent='当てる相手：'+p.targetName;$('order').textContent='';order.forEach((id,i)=>{const li=document.createElement('li');li.textContent=nameFor(id,roundRoster)+' → '+nameFor(order[(i+1)%order.length],roundRoster)+(i===order.length-1?'（先頭に戻る）':'');if(id===myId){li.setAttribute('aria-current','true');li.textContent+='（あなた）'}$('order').appendChild(li)});guessBtn.disabled=false;$('guess-status').textContent=''}
function submit(){const text=$('guess-input').value.trim();if(!text||!roundActive)return;guessBtn.disabled=true;if(isHost)handleGuess(myId,currentRoundId,text);else conn.send({type:'guess',roundId:currentRoundId,text})} guessBtn.onclick=submit;$('guess-input').onkeydown=e=>{if(e.key==='Enter')submit()};
function handleGuess(id,rid,text){rid=Number(rid);if(!isHost||!roundActive||roundEnded||rid!==currentRoundId||!roundRoster.some(p=>p.id===id)||!String(text||'').trim())return;const tid=targetOf[id],word=wordMap[tid];if(WordDetectiveLogic.isCorrectGuess(text,word)){roundEnded=true;roundActive=false;guessBtn.disabled=true;const publicWordMap=Object.fromEntries(roundRoster.map(p=>[p.id,wordMap[p.id]]));const payload={type:'game-over',roundId:rid,winnerId:id,winnerName:nameFor(id,roundRoster),targetId:tid,targetName:nameFor(tid,roundRoster),word,wordMap:publicWordMap,roster:roundRoster};showResult(payload);net.broadcast(payload)}else if(id===HOST_ID){$('guess-status').textContent='残念、違います。';guessBtn.disabled=false;$('guess-input').focus()}else net.sendTo(id,{type:'wrong-guess',roundId:rid})}
function showResult(d){roundActive=false;game.classList.add('hidden');result.classList.remove('hidden');$('result-title').textContent=d.winnerName+'さんの勝ち！';$('result-detail').textContent=d.targetName+'さんの「'+d.word+'」を当てました。';$('word-list').textContent='';d.roster.forEach(p=>{const li=document.createElement('li');li.textContent=p.name+'：'+d.wordMap[p.id];$('word-list').appendChild(li)});$('again').classList.toggle('hidden',!isHost);$('again').disabled=false;(isHost?$('again'):$('result-title')).focus()}
function abortRound(){roundActive=false;const d={type:'round-aborted',roundId:currentRoundId,reason:'参加者が切断しました。最初からやり直してください。'};net.broadcast(d);disconnect(d.reason)} function disconnect(m){roundActive=false;guessBtn.disabled=true;$('disconnect').textContent=m} $('copy').onclick=()=>navigator.clipboard&&navigator.clipboard.writeText($('room-code').textContent);$('quit').onclick=()=>location.reload();
})();
