(function(){'use strict';
const $=id=>document.getElementById(id), HOST_ID='host', REJOIN_GRACE_MS=30000; let isHost=false,myId=null,myName='',net=null,conn=null,roster=[],roundRoster=[],currentOrder=[],wordMap=null,targetOf=null,currentRoundId=0,roundActive=false,roundEnded=false,pendingOrder=new Map(),pendingPrivate=new Map(),pendingGuess=null,roomCode='',playerToken='',joinRequestId='',savedSession=RejoinStorage.load('word-detective'); const processedGuesses=new Set(),rejoinTimers=new Map();
const setup=$('setup'),lobby=$('lobby'),game=$('game'),result=$('result'),error=$('error'),status=$('status'),start=$('start'),guessBtn=$('guess-btn');
function cleanName(v){return String(v||'').trim().slice(0,10)} function nameFor(id,list=roster){const p=list.find(x=>x.id===id);return p?p.name:id}
function renderRoster(){ $('roster').textContent=''; roster.forEach(p=>{const li=document.createElement('li');li.textContent=p.name+(p.id===myId?'（あなた）':'');$('roster').appendChild(li)}); if(isHost)start.disabled=!WordDetectiveLogic.hasMinPlayers(roster)||roster.length>WordDetectiveLogic.WORD_BANK.length; }
function publicRoster(){return roster.map(p=>({id:p.id,name:p.name}))} function broadcastRoster(){net.broadcast({type:'roster',players:publicRoster()})} function fail(m){error.textContent=m;$('host').disabled=$('join').disabled=false}
function replaceId(oldId,newId){roster.forEach(p=>{if(p.id===oldId)p.id=newId});roundRoster.forEach(p=>{if(p.id===oldId)p.id=newId});currentOrder=currentOrder.map(id=>id===oldId?newId:id);if(wordMap&&wordMap[oldId]!==undefined){wordMap[newId]=wordMap[oldId];delete wordMap[oldId]}if(targetOf){if(targetOf[oldId]!==undefined){targetOf[newId]=targetOf[oldId];delete targetOf[oldId]}Object.keys(targetOf).forEach(id=>{if(targetOf[id]===oldId)targetOf[id]=newId})}}
function snapshotFor(id){const targetId=targetOf&&targetOf[id];return{type:'state-snapshot',snapshotVersion:1,phase:roundEnded?'result':(roundActive?'playing':'lobby'),scopeId:String(currentRoundId),roundId:currentRoundId,roster:publicRoster(),roundRoster:roundRoster.map(p=>({id:p.id,name:p.name})),order:currentOrder.slice(),private:roundActive&&wordMap?{myWord:wordMap[id],targetId,targetName:nameFor(targetId,roundRoster)}:null}}
$('host').onclick=()=>{myName=cleanName($('name').value);if(!myName)return fail('ニックネームを入力してください。');isHost=true;myId=HOST_ID;$('host').disabled=$('join').disabled=true;net=WordDetectiveNet.hostRoom({onCode(c){roomCode=c;WakeLockHelper.enable();$('room-code').textContent=c;$('host-wait').classList.remove('hidden');lobby.classList.remove('hidden');roster=[{id:myId,name:myName,token:'host'}];renderRoster()},onPeerConnected(){},onPeerMessage(id,d){if(!d||typeof d!=='object')return;if(d.type==='join'&&d.token){const n=cleanName(d.name);if(!n)return;const existing=roster.find(p=>p.token===d.token);if(!existing)roster.push({id,name:n,token:d.token});renderRoster();broadcastRoster();net.sendTo(id,{type:'join-ack',joinRequestId:d.joinRequestId,roomCode})}else if(d.type==='rejoin'){const p=roster.find(x=>x.token===d.token),pending=p&&rejoinTimers.get(d.token);if(!p||!pending){net.sendTo(id,{type:'rejoin-rejected',rejoinRequestId:d.rejoinRequestId});return}clearTimeout(pending.timer);rejoinTimers.delete(d.token);replaceId(p.id,id);renderRoster();broadcastRoster();net.sendTo(id,{type:'rejoin-ack',rejoinRequestId:d.rejoinRequestId,roomCode});net.sendTo(id,snapshotFor(id))}else if(d.type==='guess')handleGuess(id,d.roundId,d.text,d.actionId)},onPeerDisconnected(id){const p=roster.find(x=>x.id===id);if(!p)return;if(!roundActive){roster=WordDetectiveLogic.removePlayer(roster,id);renderRoster();broadcastRoster();return}const timer=setTimeout(()=>{rejoinTimers.delete(p.token);abortRound()},REJOIN_GRACE_MS);rejoinTimers.set(p.token,{oldPeerId:id,timer,disconnectedAt:Date.now()});$('disconnect').textContent=p.name+'さんの再接続を30秒待っています…'},onError(e){fail(PeerErrors.describe(e))},onConnectionHealthChange:healthChanged})};
function connectGuest(session){const rejoining=!!session;myName=rejoining?session.name:cleanName($('name').value);roomCode=rejoining?session.roomCode:$('code').value.trim();if(!rejoining){if(!myName)return fail('ニックネームを入力してください。');if(roomCode.length!==6)return fail('6桁のコードを入力してください。')}playerToken=rejoining?session.token:RejoinStorage.newToken();joinRequestId=RejoinStorage.newToken();$('host').disabled=$('join').disabled=true;net=WordDetectiveNet.joinRoom(roomCode,{onOwnId(id){myId=id},onConnected(c){conn=c;c.send(rejoining?{type:'rejoin',token:playerToken,name:myName,rejoinRequestId:joinRequestId}:{type:'join',name:myName,token:playerToken,joinRequestId});lobby.classList.remove('hidden');status.textContent='ホストの開始を待っています…'},onMessage:clientMessage,onDisconnected(){disconnect('ホストとの接続が切れました。ページを再読み込みすると再参加できます。')},onError(e){if(rejoining&&e&&e.type==='peer-unavailable'){RejoinStorage.clear('word-detective');savedSession=null}fail(PeerErrors.describe(e))},onConnectionHealthChange:healthChanged})}
$('join').onclick=()=>connectGuest(null);
function healthChanged(a,b){const healthy=typeof b==='boolean'?b:a;$('connection-health').classList.toggle('hidden',healthy)}
function clientMessage(d){if(!d||typeof d!=='object')return;const rid=Number(d.roundId);if(d.type==='roster'){roster=d.players;renderRoster()}else if(d.type==='join-ack'&&d.joinRequestId===joinRequestId){RejoinStorage.save('word-detective',{roomCode:d.roomCode,token:playerToken,name:myName})}else if(d.type==='rejoin-ack'&&d.rejoinRequestId===joinRequestId){RejoinStorage.save('word-detective',{roomCode:d.roomCode,token:playerToken,name:myName})}else if(d.type==='rejoin-rejected'){RejoinStorage.clear('word-detective');savedSession=null;fail('再参加の有効期限が切れました。通常参加してください。')}else if(d.type==='state-snapshot'&&d.snapshotVersion===1){roster=d.roster||[];roundRoster=d.roundRoster||[];currentOrder=Array.isArray(d.order)?d.order.slice():[];currentRoundId=Number(d.roundId)||0;renderRoster();if(d.phase==='playing'&&d.private){roundActive=true;enterGame(currentOrder,d.private)}else{setup.classList.add('hidden');lobby.classList.remove('hidden')}}else if(d.type==='order'&&Number.isInteger(rid)){d.roundId=rid;pendingOrder.set(rid,d);tryEnter(rid)}else if(d.type==='round-start'&&Number.isInteger(rid)){d.roundId=rid;pendingPrivate.set(rid,d);tryEnter(rid)}else if(d.type==='guess-ack'&&pendingGuess&&d.actionId===pendingGuess.actionId&&rid===pendingGuess.scopeId){pendingGuess.attempt.confirm();pendingGuess=null}else if(d.type==='wrong-guess'&&rid===currentRoundId){$('guess-status').textContent='残念、違います。';guessBtn.disabled=false;$('guess-input').focus()}else if(d.type==='game-over'&&rid===currentRoundId)showResult(d);else if(d.type==='round-aborted'&&rid===currentRoundId)disconnect(d.reason)}
function tryEnter(id){const o=pendingOrder.get(id),p=pendingPrivate.get(id);if(!o||!p||id<currentRoundId)return;pendingOrder.clear();pendingPrivate.clear();currentRoundId=id;roundRoster=o.roster;currentOrder=o.order.slice();enterGame(o.order,p)}
function hostStart(){if(!isHost||roundActive||!WordDetectiveLogic.hasMinPlayers(roster)||roster.length>WordDetectiveLogic.WORD_BANK.length)return;start.disabled=true;$('again').disabled=true;processedGuesses.clear();currentRoundId++;roundRoster=roster.map(p=>({id:p.id,name:p.name}));wordMap=WordDetectiveLogic.assignWords(roundRoster.map(p=>p.id));const chain=WordDetectiveLogic.buildTargetChain(roundRoster.map(p=>p.id));targetOf=chain.targetOf;currentOrder=chain.order.slice();net.broadcast({type:'order',roundId:currentRoundId,order:chain.order,roster:roundRoster});roundRoster.forEach(p=>{const payload={type:'round-start',roundId:currentRoundId,myWord:wordMap[p.id],targetId:targetOf[p.id],targetName:nameFor(targetOf[p.id],roundRoster)};if(p.id===HOST_ID)enterGame(chain.order,payload);else net.sendTo(p.id,payload)})}
function hostRerollWord(){if(!isHost||!roundActive||roundEnded||processedGuesses.size>0)return;currentRoundId++;wordMap=WordDetectiveLogic.assignWords(roundRoster.map(p=>p.id));const chain=WordDetectiveLogic.buildTargetChain(roundRoster.map(p=>p.id));targetOf=chain.targetOf;currentOrder=chain.order.slice();net.broadcast({type:'order',roundId:currentRoundId,order:chain.order,roster:roundRoster});roundRoster.forEach(p=>{const payload={type:'round-start',roundId:currentRoundId,myWord:wordMap[p.id],targetId:targetOf[p.id],targetName:nameFor(targetOf[p.id],roundRoster)};if(p.id===HOST_ID)enterGame(chain.order,payload);else net.sendTo(p.id,payload)})}
start.onclick=()=>{if(!start.disabled)hostStart()};$('again').onclick=hostStart;$('reroll-word-btn').onclick=hostRerollWord;
function enterGame(order,p){roundActive=true;roundEnded=false;setup.classList.add('hidden');lobby.classList.add('hidden');result.classList.add('hidden');game.classList.remove('hidden');$('guess-input').value='';$('word').textContent=p.myWord;$('target').textContent='当てる相手：'+p.targetName;$('order').textContent='';order.forEach((id,i)=>{const li=document.createElement('li');li.textContent=nameFor(id,roundRoster)+' → '+nameFor(order[(i+1)%order.length],roundRoster)+(i===order.length-1?'（先頭に戻る）':'');if(id===myId){li.setAttribute('aria-current','true');li.textContent+='（あなた）'}$('order').appendChild(li)});guessBtn.disabled=false;$('guess-status').textContent='';$('reroll-word-btn').classList.toggle('hidden',!isHost)}
function submit(){const text=$('guess-input').value.trim();if(!text||!roundActive||pendingGuess)return;guessBtn.disabled=true;if(isHost)handleGuess(myId,currentRoundId,text,'host-'+Date.now());else{const actionId=RejoinStorage.newToken();const payload={type:'guess',roundId:currentRoundId,scopeId:String(currentRoundId),actionId,text};const attempt=AckSend.attempt({send(){conn.send(payload)},onPending(){$('guess-status').textContent='回答を送信中です…'},onConfirmed(){$('guess-status').textContent='回答を送信しました。'},onFailed(){$('guess-status').textContent='回答を確認できませんでした。もう一度お試しください。';guessBtn.disabled=false}});pendingGuess={actionId,scopeId:currentRoundId,attempt}}} guessBtn.onclick=submit;$('guess-input').onkeydown=e=>{if(e.key==='Enter')submit()};
function handleGuess(id,rid,text,actionId){rid=Number(rid);const key=id+':'+rid+':'+String(actionId||'');if(processedGuesses.has(key)){if(id!==HOST_ID)net.sendTo(id,{type:'guess-ack',roundId:rid,scopeId:String(rid),actionId});return}if(!isHost||!roundActive||roundEnded||rid!==currentRoundId||!actionId||!roundRoster.some(p=>p.id===id)||!String(text||'').trim())return;processedGuesses.add(key);$('reroll-word-btn').classList.add('hidden');const tid=targetOf[id],word=wordMap[tid];if(WordDetectiveLogic.isCorrectGuess(text,word)){roundEnded=true;roundActive=false;guessBtn.disabled=true;const publicWordMap=Object.fromEntries(roundRoster.map(p=>[p.id,wordMap[p.id]]));const payload={type:'game-over',roundId:rid,winnerId:id,winnerName:nameFor(id,roundRoster),targetId:tid,targetName:nameFor(tid,roundRoster),word,wordMap:publicWordMap,roster:roundRoster};if(id!==HOST_ID)net.sendTo(id,{type:'guess-ack',roundId:rid,scopeId:String(rid),actionId});showResult(payload);net.broadcast(payload)}else if(id===HOST_ID){$('guess-status').textContent='残念、違います。';guessBtn.disabled=false;$('guess-input').focus()}else{net.sendTo(id,{type:'guess-ack',roundId:rid,scopeId:String(rid),actionId});net.sendTo(id,{type:'wrong-guess',roundId:rid})}}
function showResult(d){roundActive=false;game.classList.add('hidden');result.classList.remove('hidden');$('result-title').textContent=d.winnerName+'さんの勝ち！';$('result-detail').textContent=d.targetName+'さんの「'+d.word+'」を当てました。';$('word-list').textContent='';d.roster.forEach(p=>{const li=document.createElement('li');li.textContent=p.name+'：'+d.wordMap[p.id];$('word-list').appendChild(li)});$('again').classList.toggle('hidden',!isHost);$('again').disabled=false;(isHost?$('again'):$('result-title')).focus()}
function abortRound(){roundActive=false;const d={type:'round-aborted',roundId:currentRoundId,reason:'参加者が切断しました。最初からやり直してください。'};net.broadcast(d);disconnect(d.reason)} function disconnect(m){roundActive=false;guessBtn.disabled=true;$('disconnect').textContent=m} $('copy').onclick=()=>navigator.clipboard&&navigator.clipboard.writeText($('room-code').textContent);$('quit').onclick=()=>{WakeLockHelper.disable();RejoinStorage.clear('word-detective');location.reload()};
if(savedSession&&savedSession.roomCode&&savedSession.token&&savedSession.name)connectGuest(savedSession);
})();
