// data.js - YouTubeサムネイル当てクイズ 動画データバンク(DOM操作なし)
// videoId: YouTube動画ID(サムネは https://img.youtube.com/vi/<videoId>/hqdefault.jpg から直リンク)
// genre: 'vocaloid' | 'anime' | 'jpop'
// decade: '1990s' | '2000s' | '2010s' | '2020s'
//
// 各動画は実際にYouTube検索で存在・公式性を確認した上で追加している(タイトル文字列の
// 捏造なし)。本番投入分(合計150〜200件目標)は scripts/collect-candidates.js の出力を
// 人力レビューしてから追記する運用。
const VIDEO_BANK = [
  // ---- vocaloid ----
  { videoId: 'shs0rAiwsGQ', title: '千本桜', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'xxFkW3PCT5M', title: 'からくりピエロ', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'jhl5afLEKdo', title: 'ワールドイズマイン', genre: 'vocaloid', decade: '2000s' },
  { videoId: 'KushW6zvazM', title: 'ゴーストルール', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'dHXC_ahjtEE', title: 'グッバイ宣言', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'b_cuMcDWwsI', title: '裏表ラバーズ', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'P_CSdxSGfaA', title: 'アンノウン・マザーグース', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'ZB75e7vzX0I', title: 'ワールズエンド・ダンスホール', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'AS4q9yaWJkI', title: '砂の惑星', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'HOz-9FzIDf0', title: 'マトリョシカ', genre: 'vocaloid', decade: '2010s' },
  { videoId: '8oBV3jPTW4s', title: 'ロストワンの号哭', genre: 'vocaloid', decade: '2010s' },
  { videoId: '8OpCkHWnSrA', title: '延命治療', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'VWVtIg5cdDU', title: '初音ミクの消失', genre: 'vocaloid', decade: '2000s' },
  { videoId: '2b1IexhKPz4', title: 'きゅうくらりん', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'mq88yUFdVng', title: 'ラヴィ', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'EMGyiiTC7sg', title: 'カゲロウデイズ', genre: 'vocaloid', decade: '2010s' },
  { videoId: '8pGRdRhjX3o', title: '妄想感傷代償連盟', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'cm-l2h6GB8Q', title: 'KING', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'Xg-qfsKN2_E', title: 'ロキ', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'oRJBwaZ59fQ', title: 'ベノム', genre: 'vocaloid', decade: '2010s' },
  { videoId: '3sEptl-psU0', title: 'ロウワー', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'oEkGC2HV7rc', title: '劣等上等', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'aPDaFGqMX4I', title: '夜咄ディセイブ', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'adE8jVLoLPo', title: '歌姫失格', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'TXzfQ0cP1P0', title: '恋愛裁判', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'e1xCOsgWG0M', title: 'ヴァンパイア', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'Ey_NHZNYTeE', title: '脳漿炸裂ガール', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'TA5OFS_xX0c', title: 'シャルル', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'uFRPeiAEO0M', title: 'アンドロイドガール', genre: 'vocaloid', decade: '2010s' },
  { videoId: '8xFBLego17k', title: '1925', genre: 'vocaloid', decade: '2000s' },
  { videoId: 'WDUA7z3703g', title: 'Bad ∞ End ∞ Night', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'T24rF_x0TmQ', title: 'ヤラララ', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'UnIhRpIT7nc', title: 'ラグトレイン', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'xAEuACHA_QU', title: 'でぃすこみゅーたんと！', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'LqteHTWNdu0', title: 'オペラ！スペースオペラ！', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'vnw8zURAxkU', title: 'ローリンガール', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'HdC2cB_DZok', title: 'ハウトゥー世界征服', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'WysuxO4yR04', title: 'モザイクロール', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'UsIUcB46fo8', title: 'カメリア・コンプレックス', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'EHBFKhLUVig', title: '神っぽいな', genre: 'vocaloid', decade: '2020s' },
  { videoId: '9QLT1Aw_45s', title: 'フォニイ', genre: 'vocaloid', decade: '2020s' },
  { videoId: 'PqJNc9KVIZE', title: 'Tell Your World', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'uMlv9VWAxko', title: 'アンハッピーリフレイン', genre: 'vocaloid', decade: '2010s' },
  { videoId: 'jDop41Bxq2A', title: '恋は戦争', genre: 'vocaloid', decade: '2000s' },
  { videoId: 'sSHkXxADtaE', title: 'EYE', genre: 'vocaloid', decade: '2020s' },

  // ---- anime ----
  { videoId: 'o6wtDPVkKqI', title: '残酷な天使のテーゼ', genre: 'anime', decade: '1990s' },
  { videoId: 'MS7qWGeOTfY', title: '*~アスタリスク~*', genre: 'anime', decade: '2000s' },
  { videoId: 'x1FV6IrjZCY', title: '紅蓮華', genre: 'anime', decade: '2010s' },
  { videoId: '4DxL6IKmXx4', title: '炎', genre: 'anime', decade: '2020s' },
  { videoId: 'tLQLa6lM3Us', title: '残響散歌', genre: 'anime', decade: '2020s' },
  { videoId: 'q9YrWVr4dvI', title: 'Umitsuki', genre: 'anime', decade: '2020s' },
  { videoId: 'zejYD43HyQo', title: 'GO!!!', genre: 'anime', decade: '2000s' },
  { videoId: '0zLxFAlS29A', title: 'ODD FUTURE', genre: 'anime', decade: '2010s' },
  { videoId: '1tk1pqwrOys', title: '廻廻奇譚', genre: 'anime', decade: '2020s' },
  { videoId: 'M2cckDmNLMI', title: 'KICK BACK', genre: 'anime', decade: '2020s' },
  { videoId: 'a2GujJZfXpg', title: 'スパークル', genre: 'anime', decade: '2010s' },
  { videoId: 'hoxUfOTE5II', title: 'IGNITE', genre: 'anime', decade: '2010s' },
  { videoId: 'yv32__UWhVs', title: '極楽浄土', genre: 'anime', decade: '2010s' },
  { videoId: 'wfCcs0vLysk', title: 'インフェルノ', genre: 'anime', decade: '2010s' },
  { videoId: 'AW5_k_Cf4wM', title: '紅蓮の弓矢', genre: 'anime', decade: '2010s' },
  { videoId: 'r7n-L5B0bBw', title: 'ウィーアー!', genre: 'anime', decade: '1990s' },
  { videoId: '1aPOj0ERTEc', title: 'crossing field', genre: 'anime', decade: '2010s' },
  { videoId: 'BZPWmJYI_a4', title: 'ポラリス', genre: 'anime', decade: '2010s' },
  { videoId: 'j9ypaPVzrbE', title: 'ninelie', genre: 'anime', decade: '2010s' },
  { videoId: 'RNE93dieQF4', title: '革命デュアリズム', genre: 'anime', decade: '2010s' },
  { videoId: 'TSJLrHRuZVc', title: 'Shangri-La', genre: 'anime', decade: '2000s' },
  { videoId: 'azApGxaYbdc', title: 'シドニア', genre: 'anime', decade: '2010s' },
  { videoId: 'wrub7h0EGn4', title: '乙女のルートはひとつじゃない！', genre: 'anime', decade: '2020s' },
  { videoId: 'hJBHMUGI7Nc', title: 'STARS', genre: 'anime', decade: '2000s' },
  { videoId: 'qiX5DI--8bg', title: '名前のない怪物', genre: 'anime', decade: '2010s' },
  { videoId: 'LKqgY0VKZX4', title: 'Departures〜あなたにおくるアイの歌〜', genre: 'anime', decade: '2010s' },
  { videoId: 'ylYL2rDyIHc', title: 'Lv.1 職業：人間', genre: 'anime', decade: '2010s' },
  { videoId: 'RPZwWt6_unE', title: 'RESISTER', genre: 'anime', decade: '2020s' },
  { videoId: 'Lfp4ymcjKtM', title: '明日世界が終わるとしても', genre: 'anime', decade: '2020s' },
  { videoId: 'wr_k36Zmo5g', title: 'シャル・ウィ・ダンス？', genre: 'anime', decade: '2020s' },
  { videoId: 'AwXRPWmgLbU', title: '堕天', genre: 'anime', decade: '2020s' },

  // ---- jpop ----
  { videoId: 'SX_ViT4Ra7k', title: 'Lemon', genre: 'jpop', decade: '2010s' },
  { videoId: 'vLGQQbjZc5A', title: '前前前世', genre: 'jpop', decade: '2010s' },
  { videoId: 'jIBS2wHx0pc', title: '島唄', genre: 'jpop', decade: '1990s' },
  { videoId: 'CbH2F0kXgTY', title: 'ミックスナッツ', genre: 'jpop', decade: '2020s' },
  { videoId: '0xSiBpUdW4E', title: 'マリーゴールド', genre: 'jpop', decade: '2010s' },
  { videoId: 'ony539T074w', title: '白日', genre: 'jpop', decade: '2010s' },
  { videoId: 'LgLMA1MR7iE', title: '高嶺の花子さん', genre: 'jpop', decade: '2010s' },
  { videoId: 'GcpsTmDO9k0', title: 'First Love', genre: 'jpop', decade: '1990s' },
  { videoId: 'x8VYWazR5mE', title: '夜に駆ける', genre: 'jpop', decade: '2010s' },
  { videoId: 'Qp3b-RXtz4w', title: 'うっせぇわ', genre: 'jpop', decade: '2020s' },
  { videoId: 'kzZ6KXDM1RI', title: 'ドライフラワー', genre: 'jpop', decade: '2020s' },
  { videoId: 'UM9XNpgrqVk', title: '怪獣の花唄', genre: 'jpop', decade: '2020s' },
  { videoId: 'jhOVibLEDhA', title: '恋', genre: 'jpop', decade: '2010s' },
  { videoId: 'KTZ-y85Erus', title: 'だから僕は音楽を辞めた', genre: 'jpop', decade: '2010s' },
  { videoId: 'dawrQnvwMTY', title: '死ぬのがいいわ', genre: 'jpop', decade: '2020s' },
  { videoId: 'ECxBHhMc7oI', title: '本能', genre: 'jpop', decade: '1990s' },
  { videoId: 'VZBU8LvZ91Q', title: 'ありがとう', genre: 'jpop', decade: '2010s' },
  { videoId: 'PRJoAPH0ZGo', title: '栄光の架橋', genre: 'jpop', decade: '2000s' },
  { videoId: 'Dsdxxrnz1AQ', title: '桜', genre: 'jpop', decade: '2000s' },
  { videoId: '1WTy2yqKI4w', title: 'チョコレイト・ディスコ', genre: 'jpop', decade: '2000s' },
  { videoId: '51CH3dPaWXc', title: 'ロビンソン', genre: 'jpop', decade: '1990s' },
  { videoId: 'gj5Nu6feFTQ', title: '名もなき詩', genre: 'jpop', decade: '1990s' },
  { videoId: 'EqVoCfSwfUY', title: '瞳をとじて', genre: 'jpop', decade: '2000s' },
  { videoId: 'iqGHxcTPRfI', title: '花火', genre: 'jpop', decade: '2000s' },
  { videoId: '9Jh-FBYGaU4', title: 'ボーイフレンド', genre: 'jpop', decade: '2000s' },
  { videoId: 'iw_1zU2MSc8', title: 'トリセツ', genre: 'jpop', decade: '2010s' },
];

if (typeof module !== 'undefined') module.exports = VIDEO_BANK;
if (typeof window !== 'undefined') window.YoutubeThumbnailQuizData = VIDEO_BANK;
