(function () {
  'use strict';
  const $ = (id) => document.getElementById(id);
  const HOST_ID = 'host';
  const el = {};
  ['setup-screen','name-input','host-btn','join-code-input','join-btn','online-error','lobby-panel','host-wait','room-code-text','copy-code-btn','online-status','roster-list','start-btn','game-area','round-status','character-image','character-tags-list','submit-phase','guest-submit-box','nickname-input','submit-nickname-btn','fake-submitted-status','host-collect-box','collection-list','collect-next-btn','voting-phase','guest-vote-box','entries-list','vote-submitted-status','host-vote-box','vote-progress-text','tally-btn','game-connection-status','quit-btn','result-overlay','result-character-image','result-round-label','result-real-nickname','result-correct-voters','result-most-deceptive','result-tally-list','result-round-delta-list','result-scoreboard-list','result-next-btn'].forEach((id) => { el[id] = $(id); });
  let isHost=false,myId=null,myName='',net=null,conn=null,roster=[];
  let currentCharacter=null,currentRealNickname='',currentRound=0,fakes=[],entries=null,votes={},scores={},myEntryId=null,submitted=false,voted=false,phase='lobby';

  function errorText(err) { return err&&err.type==='peer-unavailable'?'そのコードの部屋が見つかりません。':'接続エラーが発生しました。'; }
  function showError(text) { el['online-error'].textContent=text; el['online-error'].classList.remove('hidden'); el['host-btn'].disabled=false; el['join-btn'].disabled=false; }
  function nameFor(id,list=roster) { const p=list.find((x)=>x.id===id); return p?p.name:id; }
  function renderRoster() { el['roster-list'].innerHTML=''; roster.forEach((p)=>{const li=document.createElement('li');li.className='roster-item';li.textContent=p.name+(p.id===myId?'（あなた）':'');el['roster-list'].appendChild(li);}); if(isHost){el['start-btn'].classList.remove('hidden');el['start-btn'].disabled=!AiNicknameGameLogic.hasMinPlayers(roster);} }
  function broadcastRoster(){net.broadcast({type:'roster',players:roster});}
  function enterLobby(){el['setup-screen'].classList.add('hidden');el['lobby-panel'].classList.remove('hidden');renderRoster();}

  el['host-btn'].onclick=()=>{const name=el['name-input'].value.trim();if(!name)return showError('名前を入力してください。');myName=name;myId=HOST_ID;isHost=true;roster=[{id:myId,name}];el['host-btn'].disabled=true;net=AiNicknameGameNet.hostRoom({onCode:(code)=>{el['room-code-text'].textContent=code;el['host-wait'].classList.remove('hidden');el['online-status'].textContent='参加を待っています…';enterLobby();},onPeerConnected:(peerId)=>net.sendTo(peerId,{type:'roster',players:roster}),onPeerMessage:handleHostMessage,onPeerDisconnected:(id)=>{roster=AiNicknameGameLogic.removePlayer(roster,id);broadcastRoster();renderRoster();},onError:(err)=>showError(errorText(err))});};
  el['join-btn'].onclick=()=>{const name=el['name-input'].value.trim(),code=el['join-code-input'].value.trim();if(!name||code.length!==6)return showError('名前と6桁コードを入力してください。');myName=name;el['join-btn'].disabled=true;net=AiNicknameGameNet.joinRoom(code,{onOwnId:(id)=>{myId=id;},onConnected:(c)=>{conn=c;conn.send({type:'join',name});el['online-status'].textContent='接続しました';enterLobby();},onMessage:handleClientMessage,onDisconnected:()=>connectionLost(),onError:(err)=>showError(errorText(err))});};
  el['copy-code-btn'].onclick=()=>navigator.clipboard&&navigator.clipboard.writeText(el['room-code-text'].textContent);
  el['quit-btn'].onclick=()=>location.reload();

  function handleHostMessage(peerId,data){if(!data||typeof data!=='object')return;if(data.type==='join'){if(phase!=='lobby')return;roster=AiNicknameGameLogic.addPlayer(roster,{id:peerId,name:String(data.name||'ゲスト').slice(0,10)});broadcastRoster();renderRoster();return;}if(data.type==='fake'&&phase==='submit')acceptFake(peerId,data.text);if(data.type==='vote'&&phase==='vote')acceptVote(peerId,data.votedEntryId);}
  function handleClientMessage(data){if(!data||typeof data!=='object')return;if(data.type==='roster'){roster=data.players;renderRoster();return;}if(data.type==='character'){myEntryId=null;enterSubmit(data);return;}if(data.type==='progress'){renderCollection(data.submittedIds);return;}if(data.type==='your-entry'){myEntryId=data.entryId;return;}if(data.type==='entries'){enterVoting(data.entries);return;}if(data.type==='vote-progress'){renderVoteProgress(data.voterIds);return;}if(data.type==='result')showResult(data);}
  function connectionLost(){el['game-connection-status'].textContent='接続が切れました。最初からやり直してください。';el['game-connection-status'].classList.remove('hidden');}

  el['start-btn'].onclick=()=>{scores={};currentRound=0;roster.forEach((p)=>{scores[p.id]=0;});startRound();};
  function startRound(){if(!isHost)return;el['result-overlay'].classList.add('hidden');currentRound++;let next=AiNicknameGameLogic.pickCharacterEntry(Math.random,AiNicknameCharacters.CHARACTER_BANK),guard=0;while(currentCharacter&&next.id===currentCharacter.id&&guard++<20)next=AiNicknameGameLogic.pickCharacterEntry(Math.random,AiNicknameCharacters.CHARACTER_BANK);currentCharacter=next;currentRealNickname=AiNicknameGameLogic.pickNickname(next.aiNicknames);fakes=[];entries=null;votes={};myEntryId=null;const data={type:'character',round:currentRound,totalRounds:AiNicknameGameLogic.ROUND_TOTAL,id:next.id,image:next.image,tags:next.tags};net.broadcast(data);enterSubmit(data);}
  function enterSubmit(data){phase='submit';el['result-overlay'].classList.add('hidden');el['lobby-panel'].classList.add('hidden');el['game-area'].classList.remove('hidden');el['submit-phase'].classList.remove('hidden');el['voting-phase'].classList.add('hidden');submitted=false;voted=false;el['nickname-input'].value='';el['nickname-input'].disabled=false;el['submit-nickname-btn'].disabled=false;el['fake-submitted-status'].classList.add('hidden');showCharacter(data);el['host-collect-box'].classList.toggle('hidden',!isHost);renderCollection([]);}
  function showCharacter(data){el['round-status'].textContent='ラウンド '+data.round+' / '+data.totalRounds;el['character-image'].src=data.image;el['character-tags-list'].innerHTML='';data.tags.forEach((tag)=>{const li=document.createElement('li');li.textContent=tag;el['character-tags-list'].appendChild(li);});}
  el['submit-nickname-btn'].onclick=()=>{if(submitted)return;const text=AiNicknameGameLogic.normalizeNickname(el['nickname-input'].value);if(!text)return;submitted=true;el['nickname-input'].disabled=true;el['submit-nickname-btn'].disabled=true;el['fake-submitted-status'].classList.remove('hidden');if(isHost)acceptFake(myId,text);else conn.send({type:'fake',text});};
  function acceptFake(authorId,text){if(!isHost||fakes.some((x)=>x.authorId===authorId))return;const clean=AiNicknameGameLogic.normalizeNickname(text);if(!clean)return;fakes.push({authorId,text:clean});const ids=fakes.map((x)=>x.authorId);net.broadcast({type:'progress',submittedIds:ids});renderCollection(ids);}
  function renderCollection(ids){el['collection-list'].innerHTML='';roster.forEach((p)=>{const li=document.createElement('li');li.className='roster-item';li.textContent=(ids.includes(p.id)?'✓ ':'… ')+p.name;el['collection-list'].appendChild(li);});el['collect-next-btn'].disabled=!isHost||!roster.every((p)=>ids.includes(p.id));}
  el['collect-next-btn'].onclick=()=>{if(!isHost||!roster.every((p)=>fakes.some((f)=>f.authorId===p.id)))return;entries=AiNicknameGameLogic.buildEntryList(currentRealNickname,fakes);entries.forEach((entry)=>{if(entry.authorId===AiNicknameGameLogic.REAL_AUTHOR)return;if(entry.authorId===myId)myEntryId=entry.id;else net.sendTo(entry.authorId,{type:'your-entry',entryId:entry.id});});const anon=entries.map((e)=>({id:e.id,text:e.text}));net.broadcast({type:'entries',entries:anon});enterVoting(anon);};
  function enterVoting(list){phase='vote';el['submit-phase'].classList.add('hidden');el['voting-phase'].classList.remove('hidden');voted=false;el['vote-submitted-status'].classList.add('hidden');el['host-vote-box'].classList.toggle('hidden',!isHost);renderEntries(list);renderVoteProgress([]);}
  function renderEntries(list){el['entries-list'].innerHTML='';list.filter((e)=>e.id!==myEntryId).forEach((entry)=>{const b=document.createElement('button');b.className='mode-btn entry-btn';b.textContent=entry.text;b.onclick=()=>{[...el['entries-list'].children].forEach((x)=>x.classList.remove('selected'));b.classList.add('selected');voted=true;el['vote-submitted-status'].classList.remove('hidden');if(isHost)acceptVote(myId,entry.id);else conn.send({type:'vote',votedEntryId:entry.id});};el['entries-list'].appendChild(b);});}
  function acceptVote(voterId,entryId){if(!isHost||!entries.some((e)=>e.id===entryId)||AiNicknameGameLogic.isSelfVote(entries,entryId,voterId))return;votes[voterId]=entryId;const ids=Object.keys(votes);net.broadcast({type:'vote-progress',voterIds:ids});renderVoteProgress(ids);}
  function renderVoteProgress(ids){el['vote-progress-text'].textContent=ids.length+' / '+roster.length+'人が投票済み';el['tally-btn'].disabled=!isHost||!roster.every((p)=>ids.includes(p.id));}
  el['tally-btn'].onclick=()=>{if(!isHost||!entries)return;const tally=AiNicknameGameLogic.tallyNicknameVotes(votes,entries),deltas=AiNicknameGameLogic.computeRoundScoreDeltas(tally,entries);scores=AiNicknameGameLogic.applyScoreDeltas(scores,deltas);const payload=Object.assign({type:'result',round:currentRound,totalRounds:AiNicknameGameLogic.ROUND_TOTAL,character:currentCharacter,entries,roundScoreDelta:deltas,totalScores:scores,isFinalRound:currentRound>=AiNicknameGameLogic.ROUND_TOTAL,roster},tally);net.broadcast(payload);showResult(payload);};
  function showResult(data){el['result-overlay'].classList.remove('hidden');el['result-character-image'].src=data.character.image;el['result-round-label'].textContent='ラウンド '+data.round+' / '+data.totalRounds;const real=data.entries.find((e)=>e.authorId===AiNicknameGameLogic.REAL_AUTHOR);el['result-real-nickname'].textContent=real?real.text:'—';el['result-correct-voters'].textContent='正解: '+(data.correctVoterIds.length?data.correctVoterIds.map((id)=>nameFor(id,data.roster)).join('、'):'なし');el['result-most-deceptive'].textContent='最も騙した人: '+(data.mostDeceptiveAuthorId?nameFor(data.mostDeceptiveAuthorId,data.roster):'なし');el['result-tally-list'].innerHTML='';data.entries.forEach((entry)=>{const li=document.createElement('li');li.className='result-tally-item'+(entry.authorId===AiNicknameGameLogic.REAL_AUTHOR?' result-tally-real':'');li.textContent=entry.text+' — '+(entry.authorId===AiNicknameGameLogic.REAL_AUTHOR?'本物':nameFor(entry.authorId,data.roster))+' / '+(data.voteCounts[entry.id]||0)+'票';el['result-tally-list'].appendChild(li);});el['result-round-delta-list'].innerHTML='';const deltaIds=Object.keys(data.roundScoreDelta);(deltaIds.length?deltaIds:['']).forEach((id)=>{const li=document.createElement('li');li.className='result-tally-item';li.textContent=id?nameFor(id,data.roster)+' : +'+data.roundScoreDelta[id]+'点':'加点なし';el['result-round-delta-list'].appendChild(li);});el['result-scoreboard-list'].innerHTML='';AiNicknameGameLogic.buildScoreboard(data.totalScores,data.roster).forEach((row)=>{const li=document.createElement('li');li.textContent=row.name+' — '+row.score+'点';el['result-scoreboard-list'].appendChild(li);});el['result-next-btn'].classList.toggle('hidden',!isHost);el['result-next-btn'].textContent=data.isFinalRound?'ゲーム終了・もう一度遊ぶ':'次のキャラへ';el['result-next-btn'].onclick=()=>{if(!isHost)return;if(data.isFinalRound){scores={};currentRound=0;roster.forEach((p)=>{scores[p.id]=0;});}startRound();};}
})();
