const assert = require('node:assert');
const L = require('./logic.js');
const { CHARACTER_BANK } = require('./characters.js');
assert.deepStrictEqual(L.shuffle([1,2,3], () => 0), [2,3,1]);
const bank = [{id:1},{id:2},{id:3}];
assert.strictEqual(L.pickCharacterEntry(() => 0, bank), bank[0]);
assert.strictEqual(L.pickCharacterEntry(() => .5, bank), bank[1]);
assert.strictEqual(L.pickCharacterEntry(() => .999, bank), bank[2]);
assert.strictEqual(L.pickNickname(['A','B','C'], () => 0), 'A');
assert.strictEqual(L.pickNickname(['A','B','C'], () => .999), 'C');
const entries = L.buildEntryList('本物', [{authorId:'a',text:'偽1'},{authorId:'b',text:'偽2'}], () => .99);
assert.strictEqual(entries.length, 3); assert.strictEqual(new Set(entries.map(e=>e.id)).size, 3);
const realId = entries.find(e=>e.authorId===L.REAL_AUTHOR).id;
const fakeA = entries.find(e=>e.authorId==='a');
const tally = L.tallyNicknameVotes({a:realId,b:fakeA.id,c:fakeA.id}, entries);
assert.deepStrictEqual(tally.correctVoterIds, ['a']); assert.strictEqual(tally.mostDeceptiveAuthorId, 'a');
assert.strictEqual(L.isSelfVote(entries, fakeA.id, 'a'), true); assert.strictEqual(L.isSelfVote(entries, realId, 'a'), false);
const deltas = L.computeRoundScoreDeltas(tally, entries);
assert.strictEqual(deltas.a, 2000); assert.deepStrictEqual(L.applyScoreDeltas({a:500}, deltas), {a:2500});
assert.deepStrictEqual(L.buildScoreboard({b:10}, [{id:'a',name:'A'},{id:'b',name:'B'}]).map(x=>x.id), ['b','a']);
assert.strictEqual(L.normalizeNickname(' 1234567890123456 '), '12345678901234');
let roster=[]; roster=L.addPlayer(roster,{id:'a',name:'A'}); roster=L.addPlayer(roster,{id:'a',name:'A'});
assert.strictEqual(roster.length,1); assert.strictEqual(L.hasMinPlayers(roster),false); assert.deepStrictEqual(L.removePlayer(roster,'a'),[]);
assert.ok(CHARACTER_BANK.length >= 40);
CHARACTER_BANK.forEach(c=>{ assert.ok(c.id&&c.image); assert.ok(Array.isArray(c.aiNicknames)&&c.aiNicknames.length>=3); assert.ok(c.aiNicknames.every(n=>typeof n==='string'&&n)); assert.ok(c.tags.length>=3&&c.tags.length<=5); });
assert.strictEqual(new Set(CHARACTER_BANK.map(c=>c.id)).size, CHARACTER_BANK.length);
const allNicknames=CHARACTER_BANK.flatMap(c=>c.aiNicknames);
assert.strictEqual(new Set(allNicknames).size, allNicknames.length);
console.log('All tests passed');
